# Generated by Django 5.1.7 on 2025-03-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0002_rename_size_planets_mass_planets_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='planets',
            name='average_temperature',
            field=models.FloatField(default=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planets',
            name='gravity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planets',
            name='orbital_period',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.FloatField(verbose_name='km'),
        ),
    ]
