# Generated by Django 5.1.7 on 2025-03-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0003_planets_average_temperature_planets_gravity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.FloatField(),
        ),
    ]
