# Generated by Django 5.1.7 on 2025-05-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0004_alter_planets_diameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePlanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seed', models.FloatField()),
                ('planet_size', models.FloatField()),
                ('orbit_radius', models.FloatField()),
                ('axial_tilt', models.FloatField()),
                ('orbit_speed', models.FloatField()),
                ('water_threshold', models.FloatField()),
                ('show_rings', models.FloatField()),
                ('color_mode', models.CharField(max_length=100)),
                ('gas_type', models.CharField(max_length=100)),
            ],
        ),
    ]
