# Generated by Django 5.1.7 on 2025-05-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0005_createplanet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createplanet',
            name='name',
            field=models.CharField(blank=True, default='Untitled', max_length=100),
        ),
    ]
